name: Daily Commit

on:
  schedule:
    - cron: '34 11 * * *'  # Runs daily at 5:30 AM UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a Commit - 23f2004010@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last_run.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f2004010@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit - $(date)"
          git push
